### ISSUE TITLE
System: Problems should retain input/solved status

### ISSUE THREAD

**Issue by jn9cn** [Team-Hacktive/Project-Hactive#5]

**Comment by gazebosx3** [comment]
We need to figure out a way of storing the information thats put in the code editor in the database

**Comment by jn9cn** [comment]
MVP: Save Button
Reach: save every 30 sec

**Comment by jn9cn** [comment]
- write the api endpoint (PUT)
- write a thunk
- make button on frontend that triggers thunk

**Comment by eseite47** [comment]
Here is what I implemented:

- SingleProblem component checks if a UserProblem association already exists of current user, current problem, and creates one if needed
- SingleProblem then fetches the problem, eager loading data from the UserProblem table, and passes it down to the Editor component
- Editor component re-renders using ComponentWillReceiveProps to set the saved using input on the state. Using other react life cycle hooks made for async issues, but let me know if you have a better solution here
- Save button in the editor will dispatch the store and to the db, to save to the UserProblem table.

This works on my machine but please test this branch and let me know what you think.
I had opened a pull request but I thought about it over night and want to change a few things with my code.
